version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:${APP_PORT}
    environment:
      - MONGO_URI=mongodb://mongodb:27017/fact_checking_be
      - MONGO_URI_TEST=mongodb://mongodb:27017/fact_checking_be_test
      - NODE_ENV=production
      - APP_NAME=${APP_NAME}
      - APP_PORT=${APP_PORT}
      - API_PREFIX=${API_PREFIX}
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
      - AUTH_JWT_TOKEN_EXPIRES_IN=${AUTH_JWT_TOKEN_EXPIRES_IN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - nesjs-network

  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE=${MONGO_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nesjs-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nesjs-network

volumes:
  mongodb_data:
  redis_data:

networks:
    nesjs-network:
      driver: bridge
