version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - MONGO_URI=mongodb://mongodb:27017/fact_checking_be
      - MONGO_URI_TEST=mongodb://mongodb:27017/fact_checking_be_test
      - NODE_ENV=development
      - APP_NAME=${APP_NAME}
      - APP_PORT=${APP_PORT}
      - API_PREFIX=${API_PREFIX}
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
      - AUTH_JWT_TOKEN_EXPIRES_IN=${AUTH_JWT_TOKEN_EXPIRES_IN}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE=${MONGO_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  mongodb_data:
  redis_data:
