version: "3"

services:
  frontend:
    build:
      context: ../fact_checking_fe
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_BASE=http://api:${APP_PORT}
      - REACT_APP_API_GET_TEXT=http://localhost:1599
      - PORT=80
    ports:
      - 80:80
    networks:
      - nesjs-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - MONGO_URI=mongodb://mongodb:27017/fact_checking_be
      - MONGO_URI_TEST=mongodb://mongodb:27017/fact_checking_be_test
      - NODE_ENV=production
      - APP_NAME=${APP_NAME}
      - APP_PORT=${APP_PORT}
      - API_PREFIX=${API_PREFIX}
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
      - AUTH_JWT_TOKEN_EXPIRES_IN=${AUTH_JWT_TOKEN_EXPIRES_IN}
    depends_on:
      - mongodb
    networks:
      - nesjs-network

  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE=${MONGO_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nesjs-network

volumes:
  mongodb_data:

networks:
    nesjs-network:
      driver: bridge
