version: "3"

services:
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
  #   environment:
  #     - discovery.type=single-node
  #     - transport.host=localhost
  #     - http.host=0.0.0.0
  #     - xpack.security.enabled=true
  #     - ELASTIC_PASSWORD=${ELASTIC_SEARCH_PWD}
  #     - KIBANA_PASSWORD=${ELASTIC_SEARCH_PWD}
  #   volumes:
  #     - elasticsearch-data:/usr/share/elasticsearch/data
  #   ports:
  #     - "9200:9200"
  #   networks:
  #     - elk
  
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.1.2
  #   environment:
  #     - ELASTICSEARCH_URL=http://elasticsearch:9200
  #     - ELASTICSEARCH_USERNAME=${ELASTIC_SEARCH_USERNAME}
  #     - ELASTICSEARCH_PASSWORD=${ELASTIC_SEARCH_PWD}
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - elk

  extract-service:
    image: rastokopal/fact-checking-extract-service:1.0.0
    ports:
      - 8080:8080

  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE=${MONGO_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: