version: "3"

services:
  extract-service:
    image: rastokopal/fact-checking-extract-service:1.0.0
    ports:
      - 8080:8080

  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE=${MONGO_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: