@startuml Components diagram

Frame "Client" {
  [client-app]
}

Cloud "Internet" {
  [detect-language-api]
}

Cloud "Cloud" {
  [api-service]
  [extract-service]
  database Redis
  database MongoDB

  [api-service] -- [extract-service] : text extraction
  [api-service] -- [Redis] : BullMQ
  [api-service] -- [MongoDB] : Uses
  [api-service] -- [detect-language-api]
}

  [client-app] -- [api-service] : REST API requests

@enduml
