name: users_service CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [main]

env:
  NODE_ENV: test
  APP_NAME:
  APP_PORT: 3000
  API_PREFIX: api
  APP_FALLBACK_LANGUAGE: en
  APP_HEADER_LANGUAGE: x-custom-lang
  FRONTEND_DOMAIN: http://localhost:3000
  BACKEND_DOMAIN: http://localhost:3000
  AUTH_JWT_SECRET: bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy4
  AUTH_JWT_TOKEN_EXPIRES_IN: 15
  MONGO_URI: mongodb://localhost/fact_checking_api
  MONGO_URI_TEST: mongodb://localhost/fact_checking_api_test
  MONGO_DB_NAME: fact_checking_api_test
  EMAIL_PORT: 587
  EMAIL_HOST: smtp-relay.sendinblue.com
  EMAIL_USERNAME: smtp-username
  EMAIL_PASSWORD: smtp-password

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['6.0']

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build App
        run: npm install

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: npm run test:e2e

  # deploy:
  #   needs: tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Build and push Docker images
  #       run: |
  #         docker build -t rastokopal/fact-checking-api:${{ github.sha }} .
  #         echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  #         docker push rastokopal/fact-checking-api:${{ github.sha }}

  #     - name: SSH and deploy
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SERVER_HOST }}
  #         username: ${{ secrets.SERVER_USERNAME }}
  #         key: ${{ secrets.SERVER_SSH_KEY }}
  #         script: |
  #           docker pull rastokopal/fact-checking-api:${{ github.sha }}
  #           docker-compose up -d --no-deps --build api
